### PR TITLE
Added Authing to Authentication and authorization

### PR DESCRIPTION
**Pull request by leinue**

### CODE REVIEW

**Comment by anaibol** [comment]
That website doesnt work

**Comment by leinue** [comment]
> That website doesnt work

Which ur country

**Comment by anaibol** [comment]
Argentina

**Comment by leinue** [comment]
> Argentina

It works in China, USA, Japan, Taiwan, Hongkong and other coutries.

**Comment by anaibol** [comment]
Now it works, do you have a link with the English version of the website?

**Comment by leinue** [comment]
> Now it works, do you have a link with the English version of the website?

We are translating

**Pull request merged**
