### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mertcanyucel**
Added Getform as an alternative service under "Forms" section.

### CODE REVIEW

**Comment by anaibol** [comment]
Hi, could you more the item to the end of the list? You can order the items alphabetically if you prefer.

**Comment by o-alexandrov** [comment]
You might want to consider requesting changes, instead of closing a PR, for easier tracking

**Comment by anaibol** [comment]
@o-alexandrov please do it

**Comment by mertcanyucel** [comment]
Opened another PR with the addition and also ordered the services in an alphabetic order. https://github.com/anaibol/awesome-serverless/pull/251

**Pull request closed without merging**
